OnlineShop/OnlineShopWebApp/Controllers/OrderController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OnlineShop.Db;
using OnlineShop.Db.Models;
using OnlineShopWebApp.ViewModels;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace OnlineShopWebApp.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderRepository orderRepository;
        private readonly ICartRepository cartRepository;
        private readonly UserManager<User> userManager;
        private readonly IPaymentMethodRepository paymentRepository;
        private readonly IAddressRepository addressRepository;
        private readonly string userId;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly IMapper mapper;
        public OrderController(IOrderRepository orderRepository,
            ICartRepository cartRepository, IPaymentMethodRepository payments,
            IAddressRepository addressRepository, UserManager<User> userManager, IHttpContextAccessor httpContextAccessor, IMapper mapper)
        {
            this.orderRepository = orderRepository;
            this.cartRepository = cartRepository;
            paymentRepository = payments;
            this.addressRepository = addressRepository;
            this.userManager = userManager;
            this.httpContextAccessor = httpContextAccessor;
            userId = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            this.mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> CreateAsync()
        {
            var currentUser = await userManager.FindByIdAsync(userId);
            var orderModel = new OrderCreateViewModel();
            orderModel.User = mapper.Map<UserViewModel>(currentUser);
            orderModel.PaymentMethodSelectList = (await paymentRepository.GetAllAsync())
                .Select(p =>
                new SelectListItem { Value = p.Id.ToString(), Text = p.Method });
            return View(orderModel);
        }


        [HttpPost]
        public async Task<IActionResult> CreateAsync(OrderCreateViewModel orderModel)
        {
            if (ModelState.IsValid)
            {
                orderModel.User.Id = Guid.Parse(userId);
                await UpdateUsersDataAsync(orderModel.User);
                await addressRepository.AddAsync(mapper.Map<Address>(orderModel.Address));
                var order = mapper.Map<Order>(orderModel);
                var cart = await cartRepository.TryGetByUserIdAsync(Guid.Parse(userId));
                order.Cart = cart;
                order.Payment = await paymentRepository.TryGetByIdAsync(orderModel.Payment.Id);
                order.Cart.Enable = false;
                await orderRepository.CreateAsync(order);
                var orderId = (await orderRepository.TryGetByUserIdAsync(Guid.Parse(userId))).Id;
                return RedirectToAction("Success", new { id = orderId });
            }
            orderModel.PaymentMethodSelectList = (await paymentRepository.GetAllAsync())
                .Select(p =>
                new SelectListItem { Value = p.Id.ToString(), Text = p.Method });
            return View(orderModel);
        }
        public async Task UpdateUsersDataAsync(UserViewModel userVM)
        {
            var currentUser = await userManager.FindByIdAsync(userVM.Id.ToString());
            
            if (currentUser != null)
            {
                currentUser.Name = userVM.Name;
                currentUser.Surname = userVM.Surname;
                currentUser.PhoneNumber = userVM.PhoneNumber;
            }
            
            await userManager.UpdateAsync(currentUser);
        }
        public IActionResult Success(int? id)
        {
            return View(id);
        }
    }
}

OnlineShop/OnlineShopWebApp/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using OnlineShop.Db;
using OnlineShop.Db.Models;
using OnlineShopWebApp.Models;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace OnlineShopWebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository productRepository;
        private readonly IFavoriteRepository favoriteRepository;
        private readonly ICompareRepository compareRepository;
        private readonly IMemoryCache memoryCache;
        public readonly string userId;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly IMapper mapper;

        public ProductController(IProductRepository productRepository, IFavoriteRepository favoriteRepository, ICompareRepository compareRepository, IHttpContextAccessor httpContextAccessor, IMapper mapper, IMemoryCache memoryCache)
        {
            this.productRepository = productRepository;
            this.favoriteRepository = favoriteRepository;
            this.compareRepository = compareRepository;
            this.httpContextAccessor = httpContextAccessor;
            userId = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            this.mapper = mapper;
            this.memoryCache = memoryCache;
        }

        public IActionResult Index(Guid id)
        {
            memoryCache.TryGetValue<Product>(id, out var product);
            return View(mapper.Map<ProductViewModel>(product));
        }

        [Authorize]
        public async Task<IActionResult> CompareAsync()
        {
            var compareProducts = await compareRepository.GelAllAsync(Guid.Parse(userId));
            if (compareProducts.Count == 0)
                return View("CompareEmpty");
            return View(mapper.Map<List<ProductViewModel>>(compareProducts));
        }

        [Authorize]
        public async Task<IActionResult> CompareAddAsync(Guid id)
        {
            await compareRepository.AddAsync(await productRepository.TryGetByIdAsync(id), Guid.Parse(userId));
            return View("Compare", mapper.Map<List<ProductViewModel>>(await compareRepository.GelAllAsync(Guid.Parse(userId))));
        }

        [Authorize]
        public async Task<IActionResult> CompareRemoveAsync(Guid id)
        {
            await compareRepository.RemoveAsync(await productRepository.TryGetByIdAsync(id), Guid.Parse(userId));
            var compareProducts = await compareRepository.GelAllAsync(Guid.Parse(userId));
            if (compareProducts.Count == 0)
                return View("CompareEmpty");
            return View("Compare", mapper.Map<List<ProductViewModel>>(compareProducts));
        }

        [Authorize]
        public async Task<IActionResult> Favorites()
        {
            var favorites = await favoriteRepository.GetAllAsync(Guid.Parse(userId));
            if (favorites.Count == 0)
                return View("FavoritesEmpty");
            return View(mapper.Map<List<ProductViewModel>>(favorites));
        }

        [Authorize]
        public async Task<IActionResult> FavoriteAddAsync(Guid id)
        {
            await favoriteRepository.AddAsync(await productRepository.TryGetByIdAsync(id), Guid.Parse(userId));
            return View("Favorites", mapper.Map<List<ProductViewModel>>(await favoriteRepository.GetAllAsync(Guid.Parse(userId))));
        }

        [Authorize]
        public async Task<IActionResult> FavoriteRemoveAsync(Guid id)
        {
            await favoriteRepository.RemoveAsync(await productRepository.TryGetByIdAsync(id), Guid.Parse(userId));
            var favorites = await favoriteRepository.GetAllAsync(Guid.Parse(userId));
            if (favorites.Count == 0)
                return View("FavoritesEmpty");
            return View("Favorites", mapper.Map<List<ProductViewModel>>(favorites));
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/Cart/CartViewComponent.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Server.IIS;
using OnlineShop.Db;
using OnlineShop.Db.Models;
using OnlineShopWebApp.Helpers;
using OnlineShopWebApp.ViewModels;
using System;
using System.Security.Claims;
using System.Threading.Tasks;

namespace OnlineShopWebApp.Views.Shared.Components.Cart
{
    public class CartViewComponent:ViewComponent
    {
        private readonly ICartRepository cartRepository;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly string userId;
        private readonly IMapper mapper;

        public CartViewComponent(ICartRepository cartRepository, IHttpContextAccessor httpContextAccessor, IMapper mapper)
        {
            this.cartRepository = cartRepository;
            this.httpContextAccessor = httpContextAccessor;
            userId = httpContextAccessor.HttpContext.User
                 .FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (userId == null)
            {
                var cookies = httpContextAccessor.HttpContext.Request.Cookies;
                if (cookies.ContainsKey("CurrentUserId"))
                {
                    userId = cookies["CurrentUserId"];
                }
                else
                {
                    userId = Guid.NewGuid().ToString();
                    httpContextAccessor.HttpContext.Response.Cookies.Append("CurrentUserId", userId);
                }
            }

            this.mapper = mapper;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        { 
            var cart = await cartRepository.TryGetByUserIdAsync(Guid.Parse(userId));
            var totalQuantity = mapper.Map<CartViewModel>(cart)?.TotalQuantity ?? 0;
            if (cart?.Enable == false)
                totalQuantity = 0;
            return View("Cart",totalQuantity);  
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Components/UserProfile/UserProfileViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using OnlineShop.Db;
using OnlineShop.Db.Models;
using OnlineShop.Db.Repositories;
using OnlineShopWebApp.Helpers;
using System;
using System.Security.Claims;
using System.Threading.Tasks;

namespace OnlineShopWebApp.Views.Shared.Components.UserProfile
{
    public class UserProfileViewComponent:ViewComponent
    {
        private readonly UserManager<User> userManager;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly string userId;
        private readonly IMemoryCache cache;
        public UserProfileViewComponent(UserManager<User> userManager, IHttpContextAccessor httpContextAccessor, IMemoryCache cache)
        {
            this.userManager = userManager;
            this.httpContextAccessor = httpContextAccessor;
            userId = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            this.cache = cache;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userName = User.Identity.Name;
            string profileImage = null;

            if (!cache.TryGetValue(userName, out profileImage))
            {
                var user = await userManager.FindByNameAsync(userName);
                profileImage = user.ProfileImagePath;

                if (profileImage != null)
                {
                    cache.Set(user.UserName, profileImage, 
                        new MemoryCacheEntryOptions().SetAbsoluteExpiration(TimeSpan.FromMinutes(30)));
                }
            }
            return View("UserProfile",profileImage);
        }
    }
}

OnlineShop/OnlineShopWebApp/Views/Shared/Footer.cshtml
<footer class="border-top footer text-muted table-info">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 my-sm-4">
                <h5 class="footer-info-header text-info text-sm-center">Контакты</h5>
                <div class="my-sm-4">
                <p class="text-info">E-mail: musicworld@mail.ru</p>
                <p class="text-info">WhatsApp: +7(999)333-12-54</p>
                </div>
            </div>
            <div class="col-sm-3 my-sm-4">
                <h5 class="footer-info-header text-info text-sm-center">Адреса магазинов</h5>
                <div class="my-sm-4">
                <p class="text-info">г. Москва, ул. Музыкальная д.5</p>
                    <p class="text-info">г. Санкт-Петербург, ул. Вдохновения д.12 (вход со двора)</p></div>
            </div>
            <div class="col-sm-3 my-sm-4">
                <h5 class="footer-info-header text-info text-sm-center">Наши соцсети</h5>
                <div class="text-sm-center my-sm-4">
                    <img src="~/images/icons/icons8-instagram-48.png" />
                    <img src="~/images/icons/icons8-vk-в-круге-48.png" />
                    <img src="~/images/icons/icons8-youtube-play-48.png" />
                    <img src="~/images/icons/icons8-телеграмма-app-48.png" />
                </div>
            </div>
            <div class="col-sm-3 my-sm-4">
                <h5 class="footer-info-header text-info text-sm-center">Обратная связь</h5>
                    <div class="my-sm-4">
                <p class="text-info">Нам важно мнение наших клиентов. Вы всегда можете оставить свое мнение о нас, заполнив <a href="#">форму обратной связи</a> или написав нам в соц сети.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 text-center">
               Copyright &copy; 2022 - Все права защищены
            </div>
        </div>
    </div>
</footer>

OnlineShop/OnlineShopWebApp/Views/Shared/Header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand text-info shop-title" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/images/logo.jpg" alt="" height="100px" class="d-inline-block align-text-center" />
                Музыкальный мир
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-sm-end">
                <ul class="navbar-nav justify-content-end">
                    @if (User.Identity.IsAuthenticated)
                    {

                        <li class="nav-item mx-sm-1">
                            <a class="nav-link text-info" asp-area="" asp-controller="Product" asp-action="Favorites"><i class="bi bi-heart"></i></a>
                        </li>
                        <li class="nav-item mx-sm-1">
                            <a class="nav-link text-info" asp-area="" asp-controller="Product" asp-action="Compare"><i class="bi bi-arrow-left-right"></i></a>
                        </li>
                    }
                    <li class="nav-item mx-sm-1">
                        @await Component.InvokeAsync("Cart")
                    </li>
                    <li class="nav-item mx-sm-1">
                        <div class="dropdown show text-info">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-info dropdown-toggle" href="#" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @await Component.InvokeAsync("UserProfile")
                                </a>
                            }
                            else
                            {
                                <a class="nav-link text-info dropdown-toggle" href="#" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-person"></i>
                                </a>
                            }
                            <div class="dropdown-menu dropdown-menu-sm-right" aria-labelledby="dropdownMenuLink">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    @if (User.IsInRole("Администратор"))
                                    {
                                        <a class="dropdown-item text-info" asp-area="Admin" asp-controller="Order" asp-action="Index">Панель администратора</a>
                                    }
                                    <a class="dropdown-item text-info" asp-area="" asp-controller="UserProfile" asp-action="Index">Личный кабинет</a>
                                    <a class="dropdown-item text-info" asp-area="" asp-controller="Account" asp-action="Logout">Выход</a>
                                }
                                else
                                {
                                    <a class="dropdown-item text-info" asp-area="" asp-controller="Account" asp-action="Login">Вход</a>
                                    <a class="dropdown-item text-info" asp-area="" asp-controller="Account" asp-action="Registration">Регистрация</a>
                                }
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

OnlineShop/OnlineShopWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShopWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans&display=swap">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @await Html.PartialAsync("Header")
    <div class="container main-content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @await Html.PartialAsync("Footer")
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Html.PartialAsync("_ValidationScriptsPartial")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>